### ISSUE TITLE
Timing issues on 250466 board

### ISSUE THREAD

**Issue by Braincell1973** [randyrossi/vicii-kawari#16] opened 2023-01-10 19:51 UTC
Using a kung fu flash and the oneload 64 v4 collection, the games ghostbustets and fix it felix freeze completely before going in game in pal and ntsc mode on a 250466 board......

The same cartridge and game file work fine when the same kawari mini is inserted into a 250407 stock board.

The freezing efdect can be seen in...... https://youtu.be/RnM1jLROvhc

Lee

**Comment by randyrossi** [comment] 2023-01-14 05:28
I'm pretty sure this is due to the PLA replacement module you are using, not the kawari.  I posted to the trouble shooting section on discord as well but I will repeat the info here:

The crashes seen with Fix it Felix Jr and Ghostbusters (and others) in the "EP20 PAL VS NTSC ON KAWARI" video posted earlier I believe are actually due to the PLA replacement module.  The problem happens with Lattice 25ns GALs (GAL20V8B). I contacted Daniël Mantione last year to report this issue.  He was able to reproduce it with the Lattice 25ns GALs but when he replaced them with Lattice 15ns or National Semiconductor 25ns GALs or Atmel 15ns GALs, it works.  I can reproduce the same hangs with Fix it Felix Jr and Ghostbusters using Lattice 25ns GALs even with a genuine VIC-II chip.  Please try your 250466 board either with a Genuine PLA + Kawari and confirm the issues go away OR use your replacement PLA + Genuine VIC-II and confirm the issues remain.  

I've done that here with my own 250407 board and can confirm it's the PLA replacement, not the VIC-2 (real or Kawari).

**Comment by randyrossi** [comment] 2023-01-23 21:10
Closing this as the PLA was the culprit.

**Closed by randyrossi** 2023-01-23 21:10 UTC
